{
 "title": "Plutus Script Evaluations (Mainnet)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Builtin Functions (V2)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "How many times V2 scripts use a built-in function",
   "type": "barchart",
   "description": "This bar chart shows for each built-in function how many times different scripts use it.",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  BUILTIN,\n  SUM(B.NUM_USAGES) AS NUM_USAGES\nFROM\n  PUBLIC.BUILTIN_VERSION_NUM_USAGES AS B\nWHERE\n  LEDGER_LANGUAGE = 2\nGROUP BY\n  BUILTIN\nORDER BY\n  NUM_USAGES DESC,\n  BUILTIN ASC"
    }
   ]
  },
  {
   "title": "How many V2 scripts use a built-in function",
   "type": "barchart",
   "description": "This bar chart shows for each built-in function how many different scripts use it.",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  BUILTIN,\n  SUM(B.NUM_SCRIPTS) AS NUM_SCRIPTS\nFROM\n  PUBLIC.BUILTIN_VERSION_NUM_SCRIPTS AS B\nWHERE\n  LEDGER_LANGUAGE = 2\nGROUP BY\n  BUILTIN\nORDER BY\n  NUM_SCRIPTS DESC,  \n  BUILTIN ASC\n"
    }
   ]
  },
  { "title": "Builtin functions (V3)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "How many V3 scripts use a built-in function",
   "type": "barchart",
   "description": "This bar chart shows for each built-in function how many different scripts use it.",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\n  BUILTIN,\n  SUM(B.NUM_SCRIPTS) AS NUM_SCRIPTS\nFROM\n  PUBLIC.BUILTIN_VERSION_NUM_SCRIPTS AS B\nWHERE\n  LEDGER_LANGUAGE = 3\nGROUP BY\n  BUILTIN\nORDER BY\n  NUM_SCRIPTS DESC,  \n  BUILTIN ASC\n"
    }
   ]
  },
  {
   "title": "How many times V3 scripts use a built-in function",
   "type": "barchart",
   "description": "This bar chart shows for each built-in function how many times different scripts use it.",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "rawSql": "SELECT\n  BUILTIN,\n  SUM(B.NUM_USAGES) AS NUM_USAGES\nFROM\n  PUBLIC.BUILTIN_VERSION_NUM_USAGES AS B\nWHERE\n  LEDGER_LANGUAGE = 3\nGROUP BY\n  BUILTIN\nORDER BY\n  NUM_USAGES DESC,\n  BUILTIN ASC"
    }
   ]
  },
  { "title": "Builtin functions (V4)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "How many V4 scripts use a built-in function",
   "type": "barchart",
   "description": "This bar chart shows for each built-in function how many different scripts use it.",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {
     "rawSql": "SELECT\n  BUILTIN,\n  SUM(B.NUM_SCRIPTS) AS NUM_SCRIPTS\nFROM\n  PUBLIC.BUILTIN_VERSION_NUM_SCRIPTS AS B\nWHERE\n  LEDGER_LANGUAGE = 4\nGROUP BY\n  BUILTIN\nORDER BY\n  NUM_SCRIPTS DESC,  \n  BUILTIN ASC\n"
    }
   ]
  },
  {
   "title": "How many times V4 scripts use a built-in function",
   "type": "barchart",
   "description": "This bar chart shows for each built-in function how many times different scripts use it.",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 139 },
   "targets": [
    {
     "rawSql": "SELECT\n  BUILTIN,\n  SUM(B.NUM_USAGES) AS NUM_USAGES\nFROM\n  PUBLIC.BUILTIN_VERSION_NUM_USAGES AS B\nWHERE\n  LEDGER_LANGUAGE = 4\nGROUP BY\n  BUILTIN\nORDER BY\n  NUM_USAGES DESC,\n  BUILTIN ASC"
    }
   ]
  }
 ]
}